name: 13 Expressions and Contexts
on: [push, pull_request, issues,workflow_dispatch]
run-name: "Expression & contexts by   @${{github.actor}}, event: ${{github.event_name}} Comment: ${{github.run_id}}"

jobs:
    runs-on-issue-and-prs:
        runs-on: ubuntu-latest
        if: contains(fromJson('["issues","pull_request"]'), github.event_name)
        steps:
            - name: Run only if issue has a bug label 
              if: contains(github.event.issue.labels.*.name, 'bug')
              run: echo ${{ join(github.event.issue.labels.*.name,',')}}

    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        # yaml will run only run if its push 
        if: github.event_name == 'push'  
        steps:
            - name: expressions  
              run: | 
                echo ${{1}}
                echo ${{'This is string'}}
                echo ${{true}}
                echo ${{ 1>2}}
                echo ${{ 'string' == 'string'}}
                echo ${{ true && false }}
            
            - name: contexts
              run: |
                echo ${{ runner}}
                echo ${{steps}}
                echo ${{job}}