name: 13 Expressions and Contexts
on: [push, pull_request, issues,workflow_dispatch]
run-name: "Expression & contexts by   @${{github.actor}}, event: ${{github.event_name}}"

jobs:
    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: expressions  
              run: | 
                echo ${{1}}
                echo ${{'This is string'}}
                echo ${{true}}
                echo ${{ 1>2}}
                echo ${{ 'string' == 'string'}}
                echo ${{ true && false }}
            
            - name: contexts
              run: |
                echo ${{ runner}}
                echo ${{steps}}
                echo ${{job}}