name: Matrix Example
on: [push]

jobs:
    build:
        continue-on-error: true
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12, 14, 16]
                os: [ubuntu-latest, windows-latest, macos-latest]
                include:
                  - node-version: 12
                    os: ubuntu-latest
                    experimental: true
                  - node-version: 16
                    os: macos-latest
                    experimental: False
                  - node-version: 14
                    os: windows-latest  
                    experimental: true
                exclude:
                  - node-version: 12
                    os: windows-latest 
                  - node-version: 16
                    os: ubuntu-latest
                  - node-version: 14
                    os: macos-latest

            fail-fast: false
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Set up Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
            node-version: ${{ matrix.node-version }}
         - name: Install dependencies
           run: echo "Installing dependencies on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"