name: Matrix Example
on: [push]

jobs:
    build:
        continue-on-error: ${{ matrix.experimental || false }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12, 14, 16]
                os: [ubuntu-latest, windows-latest, macos-latest]
                include:
                  - node-version: 12
                    os: ubuntu-latest
                    experimental: true
                # Exclude a specific combination from the matrix windowas 14 will not execute
                exclude:
                  - node-version: 14
                    os: windows-latest
            fail-fast: true
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Set up Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
            node-version: ${{ matrix.node-version }}
         - name: Install dependencies
           run: echo "Installing dependencies on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"



# matrix example with include and exclude keywords