name: Checkout 
on: [push]  
defaults:
  run:
    shell: bash

jobs:
    Javascript_Actions:
        runs-on: unbuntu-latest
        steps:
            - name : List file Before 
              run: | 
                ls -a

            - name: Checkout using Javascript_Actions
              uses: actions/checkout@v3

            - name: List file After 
              run: |    
                ls -a   

    checkout_and_display_file:
        runs-on: ubuntu-latest
        steps:
            - name : List file Before 
              run: | 
                ls -a 
            

            # this is how to use git commands to checkout the repository 
            # GitHUB_ACTOR is a default variable that holds the username of the person who triggered the workflow
            # secrets.GITHUB_TOKEN is a default secret that provides a token to authenticate on behalf of GitHub Actions
            # GITHUB_REPOSITORY.git is a default variable that holds the repository name in the format "owner/repo"

            - name: Checkout
              run: | 
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout -f main

               
            - name: List file After 
              run: |    
                ls -a

                
