name: First Workflow
# This workflow runs on every push to the repository 
on: [push] 
jobs:
    run-shell-commands:
        # runs-on specifies the type of machine to run the job on
        runs-on: ubuntu-latest
        steps:
            - name: echo a string 
              run : echo "Hello, World!"
            - name: Mutiline Command 
              run: | 
                node -v 
                npm -v 
                



 