name: First Workflow
# This workflow runs on every push to the repository 
on: [push] 
jobs:
    run-shell-commands:
        # runs-on specifies the type of machine to run the job on
        runs-on: ubuntu-latest
        # steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: echo a string 
              run : echo "Hello, World!"
            - name: Mutiline Command 
              run: | 
                node -v 
                npm -v 
    run-mac-os:
      runs-on: macos-latest
      steps:
        - name: Check macOS Version
          run: sw_vers
        - name: List Homebrew Packages
          run: | 
            brew update
            brew list


 