name: First Workflow
# This workflow runs on every push to the repository 
on: [push] 
jobs:
    run-shell-commands:
        # runs-on specifies the type of machine to run the job on
        runs-on: ubuntu-latest
        # steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: echo a string 
              run : echo "Hello, World!"
            - name: Mutiline Command 
              run: | 
                node -v 
                npm -v 
    run-mac-os:
      runs-on: macos-latest
      steps:
        - name: Check macOS Version
          run: sw_vers
        - name: List Homebrew Packages
          run: | 
            brew update
            brew list
    # An example of a job that depends on the completion of another job
    dependent-job:
      runs-on: windows-latest
      # after 'run-shell-commands' job is complete, this job will run
      needs: run-shell-commands
      steps:
        
        - name: Check Windows Version
          run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        - name: List Installed Programs
          run: powershell "Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion"      



 